name: Deploy Glue Job

on:
  push:
    branches:
      - main  # You can customize this to other branches as needed

jobs:
  deploy-glue-job:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure AWS credentials using GitHub secrets
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change this to your region

    # Upload the Glue job script to S3 (if it's not already in S3)
    # - name: Upload Glue Script to S3
    #   run: |
    #     aws s3 cp glue_scripts/your_glue_script.py s3://your-bucket-name/scripts/your_glue_script.py

    # Deploy or Update Glue Job using AWS CLI
    - name: Create or Update Glue Job
      run: |
        aws glue create-job --cli-input-json ./glue_job_1/glue_job_2.json
          
